---
- name: (RedHat) Install libselinux-python
  yum:
    name: libselinux-python
    state: installed

- name: (RedHat) Ensure SELinux is in required mode
  selinux:
    state: "{{ onec_selinux_state }}"
    policy: targeted

- name: (RedHat) Setup EPEL repository
  yum:
    name: epel-release
    state: installed

# RPM with download scripts
# https://sourceforge.net/projects/mscorefonts2/
- name: (RedHat) Install MS Core fonts
  yum:
    name: "{{ onec_mscorefonts_rpm }}"
    state: installed
  when: onec_install_mscorefonts |bool

- name: (RedHat) Install HASPd
  yum:
    name:
      - "{{ onec_haspd_package }}"
      - "{{ onec_haspd_modules_package }}"
    state: installed
  when: onec_install_haspd |bool

- name: (RedHat) Ensure HASPd service is started and enabled
  systemd:
    name: haspd
    state: started
    enabled: yes
  when: onec_install_haspd |bool

# 1C_Enterprise83-common is a major dependency of all other packages
- name: (RedHat) Gather info about installed 1C server common package
  yum:
    list: "1C_Enterprise83-common"
  register: onec_package_status

- name: (RedHat) Set different release flag
  set_fact:
    onec_different_release_installed: yes
  when: (onec_package_status.results | length) > 0 and (onec_package_status.results[0].version != onec_version or onec_package_status.results[0].release != onec_release)

- name: (RedHat) Stop and disable 1C systemd service
  systemd:
    service: srv1cv83
    state: stopped
    enabled: no
  when: onec_different_release_installed is defined

- name: (RedHat) Remove all 1C packages from different release
  yum:
    name:
      - "1C_Enterprise83-common"
      - "1C_Enterprise83-common-nls"
      - "1C_Enterprise83-server"
      - "1C_Enterprise83-server-nls"
      - "1C_Enterprise83-ws"
      - "1C_Enterprise83-ws-nls"
      - "1C_Enterprise83-crs"
    state: removed
  when: onec_different_release_installed is defined

- name: (RedHat) Install dependencies
  yum:
    name: "{{ onec_dependencies }}"
    state: installed

- name: (RedHat) Form 1C packages list
  set_fact:
    onec_packages: '{{ (onec_packages | default([])) + [ onec_packages_dir + "/1C_Enterprise83-" + item + "-" + onec_version + "-" + onec_release + ".x86_64.rpm" ] }}'
  loop: "{{ onec_server_components }}"

- name: (RedHat) Install 1C packages
  yum:
    name: "{{ onec_packages }}"
    state: installed

- name: (RedHat) Ensure 1C service is in required state
  systemd:
    service: srv1cv83
    state: "{{ onec_service_state }}"
    enabled: "{{ onec_service_enabled }}"
