---
- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: installed

- name: Ensure SELinux is in defined mode
  selinux:
    state: "{{ onec_selinux_state }}"
    policy: targeted

- name: Setup EPEL repository
  yum:
    name: epel-release
    state: installed

# RPM with download scripts
# https://sourceforge.net/projects/mscorefonts2/
- name: (RedHat) Install MS Core fonts
  yum:
    name: "{{ onec_mscorefonts_rpm }}"
    state: installed

- name: Install HASPd
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - "{{ onec_haspd_rpm }}"
    - "{{ onec_haspd_modules_rpm }}"
  when: onec_install_haspd

- name: Ensure HASPd service is started and enabled
  systemd:
    name: haspd
    state: started
    enabled: yes
  when: onec_install_haspd
